name: Deploy to EC2

on:
  push:
    branches: main

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
      - name: Build & Deploy
        env:
            PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            HOSTNAME: ${{secrets.SSH_HOST}}
            USER_NAME: ${{secrets.USER_NAME}}
      
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '

              # Now we have got the access of EC2 and we will start the deploy .
              git clone https://github.com/JTLin-nzxt/ASPNETCoreAPIServerTest.git
              cd ASPNETCoreAPIServerTest
              sudo docker stop testapi
              sudo docker rm testapi
              sudo docker rmi test-project:latest
              sudo docker build -t test-project:latest -f WebAPIExample/Dockerfile .
              sudo docker run --name testapi -d test-project:latest -p 80:80 -p 443:443 --ip 172.17.0.2
              '
